name: Build and push frontend
on:
  push

jobs:
  before:
    name: Create Github Check 🟢
    runs-on: ubuntu-latest

    steps:
    - uses: LouisBrunner/checks-action@v1.6.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Build and push production images
        status: in_progress
        details_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        output: |
          {"summary": "See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t react-test -f ./client/Dockerfile.dev ./client
      - name: Run client tests 
        run: docker run -e CI=true react-test npm test

  build:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build client production image and push on GHCR
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: hirumi16489/client:latest
      - name: Build server production image and push on GHCR
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: hirumi16489/server:latest

  after:
    name: Update GitHub Check 🟢
    needs:
      - before
      - tests
      - build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - uses: actions/checkout@v3
      - uses: LouisBrunner/checks-action@v1.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Build and push production images
          status: completed
          conclusion: ${{ env.WORKFLOW_CONCLUSION }}
          details_url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          output: |
            {"summary": "See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}